/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoaula;

import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Factura extends javax.swing.JFrame {

    private ConexionBD conexion;

    public Factura() {
        initComponents();
    }

    public Factura(int idFactura, double subtotal, double iva, double total, String MetodoDePago, String direccion, String cedula, String envio) {
        initComponents();
        conexion = new ConexionBD(); // Inicializa la conexión a la base de datos

        UtilidadesImagen.escalar(lblLogo, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/logos.jpg");

        // Inicializa los campos de texto con los valores recibidos
        fieldNroFac.setText(String.valueOf(idFactura));
        fieldSubtotal.setText(String.format("%.2f", subtotal));
        fieldIVA.setText(String.format("%.2f", iva));
        fieldTotal.setText(String.format("%.2f", total));
        fieldMetodo.setText(MetodoDePago);
        fieldDireccion.setText(direccion);
        fieldCedula.setText(cedula);
        fieldEnvio.setText(envio);
        setFechaActual();
        actualizarLabelUltimoId(); // Actualiza el JLabel con el último ID

    }

    private void setFechaActual() {
        // Obtén la fecha actual
        LocalDate fechaActual = LocalDate.now();
        // Define el formato de la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        // Establece la fecha en el campo
        fieldFechaPed.setText(fechaActual.format(formatter));
    }

    public void setDatosFactura(DefaultTableModel modeloCarrito, int[] indicesColumnas, String[] nombresColumnas) {
        DefaultTableModel modeloFactura = (DefaultTableModel) tablaFactura.getModel();

        // Limpiar datos anteriores
        modeloFactura.setRowCount(0);

        // Establecer nombres de columnas
        modeloFactura.setColumnIdentifiers(nombresColumnas);

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            Object[] rowData = new Object[indicesColumnas.length];
            for (int j = 0; j < indicesColumnas.length; j++) {
                rowData[j] = modeloCarrito.getValueAt(i, indicesColumnas[j]);
            }
            modeloFactura.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNroPed = new javax.swing.JTextField();
        fieldNroFac = new javax.swing.JTextField();
        fieldFechaPed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldTotal = new javax.swing.JTextField();
        fieldSubtotal = new javax.swing.JTextField();
        fieldIVA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldMetodo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        fieldDireccion = new javax.swing.JTextField();
        fieldCedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldEnvio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FACTURA DE COMPRA", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 100));

        tablaFactura.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFactura);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 380, 200));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Nro. Pedido:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nro. Factura:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de Pedido:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        fieldNroPed.setBorder(null);
        jPanel3.add(fieldNroPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, -1));

        fieldNroFac.setBorder(null);
        jPanel3.add(fieldNroFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, -1));

        fieldFechaPed.setBorder(null);
        jPanel3.add(fieldFechaPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 160, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("C.I Cliente:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Método de Pago:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Total:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Subtotal:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("IVA(15%):");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 170, 10));

        fieldTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldTotal.setBorder(null);
        jPanel3.add(fieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 90, -1));

        fieldSubtotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldSubtotal.setBorder(null);
        jPanel3.add(fieldSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        fieldIVA.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldIVA.setBorder(null);
        jPanel3.add(fieldIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 90, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel9.setText("¡GRACIAS POR SU COMPRA!");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        fieldMetodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldMetodo.setBorder(null);
        fieldMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMetodoActionPerformed(evt);
            }
        });
        jPanel3.add(fieldMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setBorder(null);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 160, 30));

        fieldDireccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldDireccion.setBorder(null);
        jPanel3.add(fieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 120, -1));

        fieldCedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fieldCedula.setBorder(null);
        jPanel3.add(fieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 120, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Envio:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        fieldEnvio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(fieldEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 90, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMetodoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // Crear la instancia de la clase para generar el PDF
        try {
            String rutaCarpeta = "factura";
            FacturasPDF.generarFactura(
                    rutaCarpeta,
                    fieldNroFac.getText(),
                    fieldFechaPed.getText(),
                    fieldCedula.getText(),
                    fieldDireccion.getText(),
                    fieldMetodo.getText(),
                    fieldSubtotal.getText(),
                    fieldIVA.getText(),
                    fieldTotal.getText(),
                    fieldEnvio.getText(),
                    (DefaultTableModel) tablaFactura.getModel()
            );
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
        }

        Productos pro = new Productos();
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked

    }//GEN-LAST:event_btnCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    private int obtenerUltimoId() {
        String query = "SELECT MAX(envio_id) AS ultimo_id FROM envios";
        ResultSet rs = null;
        Statement st = null;
        int ultimoId = -1;

        try {
            st = conexion.conn.createStatement();
            rs = st.executeQuery(query);

            if (rs.next()) {
                ultimoId = rs.getInt("ultimo_id");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Cierra el ResultSet y Statement en el bloque finally
            try {
                if (rs != null && !rs.isClosed()) {
                    rs.close();
                }
                if (st != null && !st.isClosed()) {
                    st.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return ultimoId;
    }

    private void actualizarLabelUltimoId() {
        int ultimoId = obtenerUltimoId();
        fieldNroPed.setText(String.valueOf(ultimoId));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JTextField fieldCedula;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JLabel fieldEnvio;
    private javax.swing.JTextField fieldFechaPed;
    private javax.swing.JTextField fieldIVA;
    private javax.swing.JTextField fieldMetodo;
    private javax.swing.JTextField fieldNroFac;
    private javax.swing.JTextField fieldNroPed;
    private javax.swing.JTextField fieldSubtotal;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tablaFactura;
    // End of variables declaration//GEN-END:variables
}
