package com.mycompany.proyectoaula;
// actualizacion

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class InsertarProductos extends javax.swing.JFrame {

    private ConexionBD conexionBD;
    private File archivoImagen;
    private Map<String, Integer> tallaStockMap = new HashMap<>();
    private Map<String, Double> tallaPrecioMap = new HashMap<>();

    public InsertarProductos() {
        initComponents();
        conexionBD = new ConexionBD(); // Inicializamos la conexión
        cargarCategorias();
        txtTallasSeleccionadas.setText("");
        cmbTallas.setEnabled(true);
        btnAgregarStock.setEnabled(false);
        btnAgregarPrecio.setEnabled(false);
        UtilidadesImagen.escalar(lblLogo, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/logo.jpg");
        UtilidadesImagen.escalar(lblVolver, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/volver.png");
        UtilidadesImagen.escalar(lblBuscar, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/buscar.png");
        tabla();
        btnInsertar.setEnabled(false);
        btnInsertarTallaNueva.setEnabled(false);
        cargarTallas();
        cmbCategoria.setSelectedIndex(-1);
        cmbTallas.setSelectedIndex(-1);
        txtTallasSeleccionadas.setText("");

        // deshabilitar todo
        cmbCategoria.setEnabled(false);
        cmbTallas.setEnabled(false);
        txtTallasSeleccionadas.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtPreciosSeleccionados.setEnabled(false);
        spnStock.setEnabled(false);
        txtStockSeleccionado.setEnabled(false);
    }

    private void tabla() {
        ((DefaultTableCellRenderer) tablaPro.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);

        tablaPro.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarCategorias() {
        Connection connection = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            connection = conexionBD.conn; // Obtén la conexión desde ConexionBD
            stmt = connection.prepareStatement("SELECT cat_nombre FROM categorias");
            rs = stmt.executeQuery();

            while (rs.next()) {
                cmbCategoria.addItem(rs.getString("cat_nombre"));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar categorías: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cierra los recursos sin cerrar la conexión
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void cargarTallas() {
        Connection connection = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            connection = conexionBD.conn; // Obtén la conexión desde ConexionBD
            stmt = connection.prepareStatement("SELECT talla_nombre FROM tallas");
            rs = stmt.executeQuery();

            while (rs.next()) {
                cmbTallas.addItem(rs.getString("talla_nombre"));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar tallas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cierra los recursos sin cerrar la conexión
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbTallas = new javax.swing.JComboBox<>();
        txtTallasSeleccionadas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtPreciosSeleccionados = new javax.swing.JTextField();
        btnSeleccionarImagen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spnStock = new javax.swing.JSpinner();
        btnAgregarPrecio = new javax.swing.JButton();
        txtRutaImagen = new javax.swing.JTextField();
        txtCarpetaDestino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnAgregarStock = new javax.swing.JButton();
        txtStockSeleccionado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPro = new javax.swing.JTable();
        btnInsertarTallaNueva = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        btnLimpiarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INGRESO DE PRODUCTOS");

        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el Stock:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione las tallas del producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el nombre del Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmbCategoria.setBorder(null);
        cmbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoriaItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 30));

        cmbTallas.setBorder(null);
        cmbTallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTallasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 30));

        txtTallasSeleccionadas.setEditable(false);
        txtTallasSeleccionadas.setBorder(null);
        jPanel1.add(txtTallasSeleccionadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese el precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtNombreProducto.setBorder(null);
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 30));

        txtPreciosSeleccionados.setEditable(false);
        txtPreciosSeleccionados.setBorder(null);
        jPanel1.add(txtPreciosSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 300, 30));

        btnSeleccionarImagen.setBackground(new java.awt.Color(0, 0, 0));
        btnSeleccionarImagen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.setBorder(null);
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 130, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione la categoría del producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        spnStock.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnStockStateChanged(evt);
            }
        });
        jPanel1.add(spnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 30));

        btnAgregarPrecio.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarPrecio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAgregarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPrecio.setText("Agregar Precio");
        btnAgregarPrecio.setBorder(null);
        btnAgregarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 30));

        txtRutaImagen.setEditable(false);
        txtRutaImagen.setBorder(null);
        jPanel1.add(txtRutaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 160, 30));

        txtCarpetaDestino.setEditable(false);
        txtCarpetaDestino.setBorder(null);
        jPanel1.add(txtCarpetaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 300, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Carpeta Destino:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 150, -1));

        lblImagen.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 250, 270));

        btnInsertar.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("Insertar Producto Nuevo");
        btnInsertar.setBorder(null);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 250, 40));

        btnAgregarStock.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarStock.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAgregarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarStock.setText("Agregar Stock");
        btnAgregarStock.setBorder(null);
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 120, 30));

        txtStockSeleccionado.setEditable(false);
        txtStockSeleccionado.setBorder(null);
        jPanel1.add(txtStockSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 300, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 160, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 300, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 300, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 300, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Productos y Tallas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stock", "nombre", "talla", "precio", "categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPro);
        if (tablaPro.getColumnModel().getColumnCount() > 0) {
            tablaPro.getColumnModel().getColumn(0).setResizable(false);
            tablaPro.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaPro.getColumnModel().getColumn(1).setResizable(false);
            tablaPro.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaPro.getColumnModel().getColumn(2).setResizable(false);
            tablaPro.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaPro.getColumnModel().getColumn(3).setResizable(false);
            tablaPro.getColumnModel().getColumn(3).setPreferredWidth(100);
            tablaPro.getColumnModel().getColumn(4).setResizable(false);
            tablaPro.getColumnModel().getColumn(4).setPreferredWidth(0);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, 400));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 380, 450));

        btnInsertarTallaNueva.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertarTallaNueva.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnInsertarTallaNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarTallaNueva.setText("Insertar Talla Nueva");
        btnInsertarTallaNueva.setBorder(null);
        btnInsertarTallaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarTallaNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertarTallaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 250, 40));

        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 40, 40));

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiarCampos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.setBorder(null);
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrecioActionPerformed
        String precio = txtPrecio.getText();
        if (!precio.isEmpty() && !precio.equals("0")) {
            agregarPrecio();
            btnAgregarPrecio.setEnabled(false);
            btnAgregarStock.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un precio mayor a 0");
        }
    }//GEN-LAST:event_btnAgregarPrecioActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        seleccionarImagen();
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void cmbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoriaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            actualizarRutaDestino();
        }
    }//GEN-LAST:event_cmbCategoriaItemStateChanged

    private void cmbTallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTallasActionPerformed
        actualizarTallasSeleccionadas();
        if (cmbTallas.getSelectedItem() != null) {
            btnAgregarPrecio.setEnabled(true);
//            cmbTallas.setEnabled(false); // Deshabilitar el combobox
        }
    }//GEN-LAST:event_cmbTallasActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        insertarProducto();
        limpiarCampos();

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void spnStockStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnStockStateChanged
        JSpinner spinner = (JSpinner) evt.getSource(); // Obtener el spinner que ha disparado el evento
        int valorActual = (Integer) spinner.getValue(); // Obtener el valor actual del spinner

        // Validar el valor del spinner
        if (valorActual < 0) {
            // Si el valor es negativo, establecer el valor en 0
            spinner.setValue(0);
        }
    }//GEN-LAST:event_spnStockStateChanged

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        int stock = (int) spnStock.getValue();
        if (stock > 0) {
            agregarStock();
            btnAgregarStock.setEnabled(false);
            cmbTallas.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un stock mayor a 0");
        }
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        MenuAdmin admin = new MenuAdmin();
        admin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnInsertarTallaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarTallaNuevaActionPerformed
        Connection connection = null;
        PreparedStatement stmt = null;

        try {
            // Obtener los valores de los campos de entrada
            String nombreProducto = txtNombreProducto.getText(); // Asegúrate de tener un JTextField con este nombre
            String tallas = txtTallasSeleccionadas.getText(); // Asegúrate de tener un JTextField con este nombre
            String stocks = txtStockSeleccionado.getText(); // Asegúrate de tener un JTextField con este nombre
            String precios = txtPreciosSeleccionados.getText(); // Asegúrate de tener un JTextField con este nombre

            // Validar entradas
            if (nombreProducto == null || nombreProducto.isEmpty()
                    || tallas == null || tallas.isEmpty()
                    || stocks == null || stocks.isEmpty()
                    || precios == null || precios.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Obtener la conexión
            connection = conexionBD.conn; // Asegúrate de que `conexionBD.conn` esté correctamente configurado

            // Preparar la llamada al procedimiento almacenado
            stmt = connection.prepareCall("{CALL AgregarTallasAProductoExistente(?, ?, ?, ?)}");
            stmt.setString(1, nombreProducto);
            stmt.setString(2, tallas);
            stmt.setString(3, stocks);
            stmt.setString(4, precios);

            // Ejecutar el procedimiento almacenado
            stmt.executeUpdate();

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Tallas agregadas al producto exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al agregar las tallas al producto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar los recursos sin cerrar la conexión
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnInsertarTallaNuevaActionPerformed

    private void limpiarCampos() {

        // Obtener el modelo de la tabla y limpiar sus datos
        DefaultTableModel model = (DefaultTableModel) tablaPro.getModel();
        model.setRowCount(0); // Limpiar la tabla
        txtNombreProducto.setText("");
        cmbCategoria.setSelectedIndex(-1);
        cmbTallas.setSelectedIndex(-1);
        txtTallasSeleccionadas.setText("");
        txtPrecio.setText("");
        txtPreciosSeleccionados.setText("");
        spnStock.setValue(0);
        txtStockSeleccionado.setText("");
        lblImagen.setIcon(null);
    }

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        Connection connection = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        String nombreProducto = txtNombreProducto.getText();

        if (nombreProducto != null && !nombreProducto.isEmpty()) {
            try {
                connection = conexionBD.conn; // Obtén la conexión desde ConexionBD

                // 1. Ejecutar el procedimiento almacenado para obtener los detalles del producto
                stmt = connection.prepareCall("{call ObtenerDetallesProducto(?)}");
                stmt.setString(1, nombreProducto);
                rs = stmt.executeQuery();

                // Obtener el modelo de la tabla
                DefaultTableModel model = (DefaultTableModel) tablaPro.getModel();
                model.setRowCount(0); // Limpiar la tabla antes de insertar nuevos datos

                // Verificar si hay resultados
                if (!rs.isBeforeFirst()) {
                    // Si no hay resultados, mostrar un mensaje y limpiar los elementos del JComboBox
                    JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    btnInsertar.setEnabled(true);
                    btnInsertarTallaNueva.setEnabled(false);
                    cmbTallas.removeAllItems();
                    cargarTallas();
                    cmbCategoria.setEnabled(true);
                    cmbTallas.setSelectedIndex(-1);
                    cmbCategoria.setSelectedIndex(-1);
                    txtTallasSeleccionadas.setText("");
                    btnSeleccionarImagen.setEnabled(true);

                    cmbTallas.setEnabled(true);
                    txtTallasSeleccionadas.setEnabled(true);
                    txtPrecio.setEnabled(true);
                    txtPreciosSeleccionados.setEnabled(true);
                    spnStock.setEnabled(true);
                    txtStockSeleccionado.setEnabled(true);
                    lblImagen.setIcon(null);
                } else {
                    // Recorrer los resultados y añadirlos a la tabla
                    while (rs.next()) {
                        String categoria = rs.getString("nombre_producto");
                        String nombre = rs.getString("categoria");
                        String talla = rs.getString("talla");
                        double precio = rs.getDouble("precio");
                        int stock = rs.getInt("stock");

                        model.addRow(new Object[]{nombre, categoria, talla, precio, stock});
                        cmbCategoria.setSelectedItem(nombre); // Asignar la categoría al JComboBox
                    }

                    // 2. Actualizar el JComboBox con las tallas que no pertenecen al producto encontrado
                    // Primero, cerramos el ResultSet y PreparedStatement para la primera consulta
                    rs.close();
                    stmt.close();

                    // Consulta para obtener las tallas que no pertenecen al producto buscado
                    String query = "SELECT t.talla_nombre "
                            + "FROM tallas t "
                            + "WHERE t.talla_nombre NOT IN ("
                            + "    SELECT ta.talla_nombre "
                            + "    FROM productostallas pt "
                            + "    JOIN tallas ta ON pt.fk_talla_id = ta.talla_id "
                            + "    JOIN productos p ON pt.fk_pro_id = p.pro_id "
                            + "    WHERE p.pro_nombrePro = ?"
                            + ")";

                    stmt = connection.prepareStatement(query);
                    stmt.setString(1, nombreProducto);
                    rs = stmt.executeQuery();

                    // Actualizar el JComboBox con las tallas
                    cmbTallas.removeAllItems();
                    while (rs.next()) {
                        String talla = rs.getString("talla_nombre");
                        cmbTallas.addItem(talla);
                    }

                    cmbTallas.setEnabled(true);
                    txtTallasSeleccionadas.setText("");
                    btnInsertarTallaNueva.setEnabled(true);
                    btnInsertar.setEnabled(false);
                    cmbCategoria.setEnabled(false);
                    cmbTallas.setSelectedIndex(-1);

                    cmbTallas.setEnabled(true);
                    txtTallasSeleccionadas.setEnabled(true);
                    txtPrecio.setEnabled(true);
                    txtPreciosSeleccionados.setEnabled(true);
                    spnStock.setEnabled(true);
                    txtStockSeleccionado.setEnabled(true);
                    btnSeleccionarImagen.setEnabled(false);

                    // Mostrar la imagen después de haber actualizado la categoría y las tallas
                    mostrarImagen();
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al obtener los detalles del producto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(InsertarProductos.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                // Cierra los recursos sin cerrar la conexión
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (stmt != null) {
                        stmt.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el nombre del producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
        cmbCategoria.setEnabled(false);
        cmbTallas.setEnabled(false);
        txtTallasSeleccionadas.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtPreciosSeleccionados.setEnabled(false);
        spnStock.setEnabled(false);
        txtStockSeleccionado.setEnabled(false);
        btnInsertar.setEnabled(false);
        btnInsertarTallaNueva.setEnabled(false);

    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void mostrarImagen() throws IOException {
        String productoSeleccionado = txtNombreProducto.getText();
        String categoriaSeleccionada = (String) cmbCategoria.getSelectedItem();

        if (productoSeleccionado != null && categoriaSeleccionada != null) {
            // Transformar el nombre del producto para coincidir con el nombre del archivo de imagen
            String imageName = productoSeleccionado.toLowerCase().replace(" ", "_");
            String[] formatos = {".jpg", ".jpeg", ".png"};
            String imagePath = "";

            // Determinar la ruta de la imagen según la categoría
            switch (categoriaSeleccionada.toLowerCase()) {
                case "pantalones":
                    imagePath = "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/Pantalones/";
                    break;
                case "camisas":
                    imagePath = "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/Camisas/";
                    break;
                case "chaquetas":
                    imagePath = "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/Chaquetas/";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Categoría no válida.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
            }

            File imageFile = null;

            // Buscar la imagen con diferentes extensiones
            for (String formato : formatos) {
                File tempFile = new File(imagePath + imageName + formato);
                if (tempFile.exists()) {
                    imageFile = tempFile;
                    break;
                }
            }

            if (imageFile != null && imageFile.exists()) {
                Image image = ImageIO.read(imageFile);
                // Redimensionar la imagen si es necesario
                Image scaledImage = image.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(scaledImage));
            } else {
                lblImagen.setIcon(null); // No se encontró la imagen
                lblImagen.setText("Imagen no encontrada para el producto seleccionado.");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarProductos().setVisible(true);
            }
        });
    }

    private void agregarStock() {
        Integer stock = (Integer) spnStock.getValue();
        String tallaSeleccionada = (String) cmbTallas.getSelectedItem();

        if (tallaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una talla para agregar el stock.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar que el stock no sea negativo
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "El stock no puede ser negativo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar que el stock se ingrese para la talla seleccionada
        tallaStockMap.put(tallaSeleccionada, stock);

        // Actualizar el JTextField de stock seleccionado
        actualizarStockSeleccionado();

        // Limpiar el JSpinner
        spnStock.setValue(0);
    }

    private void actualizarStockSeleccionado() {
        StringBuilder stockBuilder = new StringBuilder();

        // Agregar el stock en el orden que fueron seleccionados
        for (String talla : txtTallasSeleccionadas.getText().split(",\\s*")) {
            Integer stock = tallaStockMap.get(talla);
            if (stock != null) {
                stockBuilder.append(stock).append(", ");
            }
        }

        // Eliminar la última coma y espacio
        if (stockBuilder.length() > 0) {
            stockBuilder.setLength(stockBuilder.length() - 2);
        }

        txtStockSeleccionado.setText(stockBuilder.toString());
    }

    private void agregarPrecio() {
        String precioTexto = txtPrecio.getText();
        String tallaSeleccionada = (String) cmbTallas.getSelectedItem();

        if (tallaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una talla para agregar el precio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double precio = Double.parseDouble(precioTexto);

            // Verificar que el precio se ingrese para la talla seleccionada
            tallaPrecioMap.put(tallaSeleccionada, precio);

            // Actualizar el JTextField de precios seleccionados
            actualizarPreciosSeleccionados();

            // Limpiar el campo de precio
            txtPrecio.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarPreciosSeleccionados() {
        StringBuilder preciosBuilder = new StringBuilder();

        // Agregar los precios en el orden que fueron seleccionados
        for (String talla : txtTallasSeleccionadas.getText().split(",\\s*")) {
            Double precio = tallaPrecioMap.get(talla);
            if (precio != null) {
                preciosBuilder.append(precio).append(", ");
            }
        }

        // Eliminar la última coma y espacio
        if (preciosBuilder.length() > 0) {
            preciosBuilder.setLength(preciosBuilder.length() - 2);
        }

        txtPreciosSeleccionados.setText(preciosBuilder.toString());
    }

    private void seleccionarImagen() {
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoImagen = fileChooser.getSelectedFile();
            String productName = txtNombreProducto.getText().replace(' ', '_');
            String newImageName = productName + "." + archivoImagen.getName().substring(archivoImagen.getName().lastIndexOf('.') + 1);
            File newImageFile = new File(archivoImagen.getParent(), newImageName);
            archivoImagen.renameTo(newImageFile);
            txtRutaImagen.setText(newImageFile.getAbsolutePath());

            // Mostrar la imagen en el JLabel
            try {
                ImageIcon imageIcon = new ImageIcon(newImageFile.getAbsolutePath());
                Image image = imageIcon.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(image));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void actualizarRutaDestino() {
        String categoriaSeleccionada = (String) cmbCategoria.getSelectedItem();

        switch (categoriaSeleccionada) {
            case "Pantalones":
                txtCarpetaDestino.setText("C:\\Users\\USER\\OneDrive\\Escritorio\\ProyectoAula\\imgs\\Pantalones");
                break;
            case "Camisas":
                txtCarpetaDestino.setText("C:\\Users\\USER\\OneDrive\\Escritorio\\ProyectoAula\\imgs\\Camisas");
                break;
            case "Chaquetas":
                txtCarpetaDestino.setText("C:\\Users\\USER\\OneDrive\\Escritorio\\ProyectoAula\\imgs\\Chaquetas");
                break;
            default:
                txtCarpetaDestino.setText("C:\\Users\\USER\\OneDrive\\Escritorio\\ProyectoAula\\imgs\\Otros");
                break;
        }
    }

    private void actualizarTallasSeleccionadas() {
        String tallaSeleccionada = (String) cmbTallas.getSelectedItem();
        String[] tallasArray = txtTallasSeleccionadas.getText().split(",\\s*");

        // Verificar si la talla ya está en el texto
        boolean yaSeleccionada = false;
        for (String talla : tallasArray) {
            if (talla.equals(tallaSeleccionada)) {
                yaSeleccionada = true;
                break;
            }
        }

        if (!yaSeleccionada) {
            String tallasTextoActual = txtTallasSeleccionadas.getText();
            if (tallasTextoActual.isEmpty()) {
                txtTallasSeleccionadas.setText(tallaSeleccionada);
            } else {
                txtTallasSeleccionadas.setText(tallasTextoActual + ", " + tallaSeleccionada);
            }
        }
    }

    private void insertarProducto() {
        String nombreProducto = txtNombreProducto.getText();
        String categoria = (String) cmbCategoria.getSelectedItem();
        String tallasTexto = txtTallasSeleccionadas.getText();
        String preciosTexto = txtPreciosSeleccionados.getText();
        String stockTexto = txtStockSeleccionado.getText();
        String rutaImagen = txtRutaImagen.getText();
        String carpetaDestino = txtCarpetaDestino.getText();

        if (nombreProducto.isEmpty() || categoria == null || tallasTexto.isEmpty() || preciosTexto.isEmpty() || stockTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] tallasArray = tallasTexto.split(",\\s*");
        String[] preciosArray = preciosTexto.split(",\\s*");
        String[] stockArray = stockTexto.split(",\\s*");

        if (tallasArray.length != preciosArray.length || tallasArray.length != stockArray.length) {
            JOptionPane.showMessageDialog(this, "El número de tallas, precios y stock no coincide.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir arrays a textos separados por comas
        String tallasTextoSQL = String.join(",", tallasArray);
        String preciosTextoSQL = String.join(",", preciosArray);
        String stockTextoSQL = String.join(",", stockArray);

        ConexionBD conexion = new ConexionBD();
        Connection conn = conexion.conn;

        try {
            if (conn != null) {
                conn.setAutoCommit(false);

                // Llamar al procedimiento almacenado
                String callProcedureSQL = "{CALL InsertarProductoConTallasYPrecios(?, ?, ?, ?, ?)}";
                try (PreparedStatement cstmt = conn.prepareCall(callProcedureSQL)) {
                    cstmt.setString(1, nombreProducto);
                    cstmt.setString(2, categoria);
                    cstmt.setString(3, tallasTextoSQL);
                    cstmt.setString(4, stockTextoSQL);
                    cstmt.setString(5, preciosTextoSQL);
                    cstmt.execute();
                }

                conn.commit();
                JOptionPane.showMessageDialog(this, "Producto insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Mover imagen a la carpeta de destino
                if (rutaImagen != null && !rutaImagen.isEmpty()) {
                    File archivoImagen = new File(rutaImagen);
                    if (archivoImagen.exists()) {
                        File destino = new File(carpetaDestino, archivoImagen.getName());
                        try {
                            Files.copy(archivoImagen.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);
                            JOptionPane.showMessageDialog(this, "Imagen guardada con éxito en " + destino.getAbsolutePath(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        } catch (IOException ioEx) {
                            JOptionPane.showMessageDialog(this, "Error al guardar la imagen: " + ioEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            ioEx.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El archivo de imagen seleccionado no existe.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            conexion.desconectar();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPrecio;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertarTallaNueva;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbTallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTable tablaPro;
    private javax.swing.JTextField txtCarpetaDestino;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPreciosSeleccionados;
    private javax.swing.JTextField txtRutaImagen;
    private javax.swing.JTextField txtStockSeleccionado;
    private javax.swing.JTextField txtTallasSeleccionadas;
    // End of variables declaration//GEN-END:variables
}
