/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoaula;

/**
 *
 * @author USER
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        this.setLocationRelativeTo(this);
        UtilidadesImagen.escalar(lblLogo, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/logo.jpg");
        UtilidadesImagen.escalar(lblVolver, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/salir.png");
        UtilidadesImagen.escalar(lblCarrito, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/carrito.png");
        UtilidadesImagen.escalar(lblPerfil, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/perfil.png");

        UtilidadesImagen.escalar(lblCamisas, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/camisetas.png");
        UtilidadesImagen.escalar(lblPantalones, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/pants.png");
        UtilidadesImagen.escalar(lblChaquetas, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/zapas.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCarrito = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPantalones = new javax.swing.JLabel();
        btnPants = new javax.swing.JButton();
        btnCamisas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblCamisas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblChaquetas = new javax.swing.JLabel();
        btnChaquetas = new javax.swing.JButton();
        lblPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIENDA DE ROPA DERICK");

        lblVolver.setText("jLabel1");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCIONE SU PREFERENCIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 36))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarritoMouseClicked(evt);
            }
        });
        jPanel4.add(lblCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 50, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        lblPantalones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPantalones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPantalonesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPantalones, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPantalones, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 260));

        btnPants.setBackground(new java.awt.Color(0, 0, 0));
        btnPants.setFont(new java.awt.Font("Roboto", 1, 23)); // NOI18N
        btnPants.setForeground(new java.awt.Color(255, 255, 255));
        btnPants.setText("Explorar Pantalones");
        btnPants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantsActionPerformed(evt);
            }
        });
        jPanel4.add(btnPants, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 40));

        btnCamisas.setBackground(new java.awt.Color(0, 0, 0));
        btnCamisas.setFont(new java.awt.Font("Roboto", 1, 23)); // NOI18N
        btnCamisas.setForeground(new java.awt.Color(255, 255, 255));
        btnCamisas.setText("Explorar Camisetas");
        btnCamisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamisasActionPerformed(evt);
            }
        });
        jPanel4.add(btnCamisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 240, 40));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        lblCamisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCamisas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCamisasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCamisas, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCamisas, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 240, 260));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        lblChaquetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChaquetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChaquetasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChaquetas, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChaquetas, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 240, 260));

        btnChaquetas.setBackground(new java.awt.Color(0, 0, 0));
        btnChaquetas.setFont(new java.awt.Font("Roboto", 1, 23)); // NOI18N
        btnChaquetas.setForeground(new java.awt.Color(255, 255, 255));
        btnChaquetas.setText("Explorar Chaquetas");
        btnChaquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChaquetasActionPerformed(evt);
            }
        });
        jPanel4.add(btnChaquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 240, 40));

        lblPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilMouseClicked(evt);
            }
        });
        jPanel4.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 780, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        VentanaLogin log = new VentanaLogin();
        log.setVisible(true);
        CarritoData.clear();
        this.dispose();

    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarritoMouseClicked
        Carrito car = new Carrito();
        car.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblCarritoMouseClicked

    private void btnPantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantsActionPerformed
        Pantalones pants = new Pantalones();
        pants.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnPantsActionPerformed

    private void btnCamisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamisasActionPerformed
        Camisetas camis = new Camisetas();
        camis.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCamisasActionPerformed

    private void btnChaquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChaquetasActionPerformed
        Chaquetas zapas = new Chaquetas();
        zapas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnChaquetasActionPerformed

    private void lblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseClicked
        Perfil perfil = new Perfil();
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPerfilMouseClicked

    private void lblPantalonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPantalonesMouseClicked
        Pantalones pants = new Pantalones();
        pants.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPantalonesMouseClicked

    private void lblCamisasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCamisasMouseClicked
        Camisetas camisa = new Camisetas();
        camisa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCamisasMouseClicked

    private void lblChaquetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChaquetasMouseClicked
        Chaquetas chaquetas = new Chaquetas();
        chaquetas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblChaquetasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamisas;
    private javax.swing.JButton btnChaquetas;
    private javax.swing.JButton btnPants;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCamisas;
    private javax.swing.JLabel lblCarrito;
    private javax.swing.JLabel lblChaquetas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPantalones;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblVolver;
    // End of variables declaration//GEN-END:variables
}
