/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoaula;

import com.toedter.calendar.JDateChooser;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    private ConexionBD conexion;

    public Reportes() {
        initComponents();

        UtilidadesImagen.escalar(lblLogo, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/logo.jpg");
        UtilidadesImagen.escalar(lblVolver, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/volver.png");
        UtilidadesImagen.escalar(btnListar, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/listar.png");
        UtilidadesImagen.escalar(btnListarPro, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/listar.png");
        UtilidadesImagen.escalar(btnListarCli, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/listar.png");

        conexion = new ConexionBD();
        fechaMin.setDateFormatString("yyyy-MM-dd");
        fechaMax.setDateFormatString("yyyy-MM-dd");
        fechaMinPro.setDateFormatString("yyyy-MM-dd");
        fechaMaxPro.setDateFormatString("yyyy-MM-dd");
        fechaMinCli.setDateFormatString("yyyy-MM-dd");
        fechaMaxCli.setDateFormatString("yyyy-MM-dd");

        btnImprimir.setEnabled(false);
        btnImprimirCli.setEnabled(false);
        btnImprimirPro.setEnabled(false);
        tabla();
    }

    private void tabla() {
        // Centrar los encabezados de las columnas
        ((DefaultTableCellRenderer) tablaListaFacturas.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        ((DefaultTableCellRenderer) tablaListaProductos.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        ((DefaultTableCellRenderer) TablaTotalClientes.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        ((DefaultTableCellRenderer) tablaListaClientes.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
        // Deshabilitar el movimiento de columnas
        tablaListaFacturas.getTableHeader().setReorderingAllowed(false);
        tablaListaProductos.getTableHeader().setReorderingAllowed(false);
        TablaTotalClientes.getTableHeader().setReorderingAllowed(false);
        tablaListaClientes.getTableHeader().setReorderingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListaFacturas = new javax.swing.JTable();
        fechaMin = new com.toedter.calendar.JDateChooser();
        fechaMax = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnListar = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnCalcularGanancias = new javax.swing.JButton();
        fieldTotalGanancias = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnListarPro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaMinPro = new com.toedter.calendar.JDateChooser();
        fechaMaxPro = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaListaProductos = new javax.swing.JTable();
        btnImprimirPro = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fechaMinCli = new com.toedter.calendar.JDateChooser();
        fechaMaxCli = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnListarCli = new javax.swing.JLabel();
        btnImprimirCli = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaListaClientes = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaTotalClientes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTES DERICK");

        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });

        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 66));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione el Reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 24))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaListaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro.Fac", "Cedula Cliente", "Fecha", "Método de Pago", "Subtotal", "IVA", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaListaFacturas);
        if (tablaListaFacturas.getColumnModel().getColumnCount() > 0) {
            tablaListaFacturas.getColumnModel().getColumn(0).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(0).setPreferredWidth(5);
            tablaListaFacturas.getColumnModel().getColumn(0).setHeaderValue("Nro.");
            tablaListaFacturas.getColumnModel().getColumn(1).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(2).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(3).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(4).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(5).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(5).setHeaderValue("IVA");
            tablaListaFacturas.getColumnModel().getColumn(6).setResizable(false);
            tablaListaFacturas.getColumnModel().getColumn(6).setHeaderValue("Total");
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 6, 588, 343));
        jPanel3.add(fechaMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 152, -1));
        jPanel3.add(fechaMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        jLabel2.setText("Seleccionar Fecha Inicio:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("Seleccionar Fecha Fin:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Intervalo de Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 12))); // NOI18N

        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 120));

        btnImprimir.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimir.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("IMPRIMIR REPORTE");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 50));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ganancias Totales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 14))); // NOI18N

        btnCalcularGanancias.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcularGanancias.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCalcularGanancias.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularGanancias.setText("Calcular Ganancias");
        btnCalcularGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGananciasActionPerformed(evt);
            }
        });

        fieldTotalGanancias.setEditable(false);
        fieldTotalGanancias.setBackground(new java.awt.Color(255, 255, 255));
        fieldTotalGanancias.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        fieldTotalGanancias.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldTotalGanancias)
                    .addComponent(btnCalcularGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalcularGanancias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldTotalGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 120));

        jTabbedPane1.addTab("Listado de Facturas", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Intervalo de Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 12))); // NOI18N

        btnListarPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarProMouseClicked(evt);
            }
        });

        jLabel4.setText("Seleccionar Fecha Inicio:");

        jLabel5.setText("Seleccionar Fecha Fin:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaMinPro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(fechaMaxPro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(fechaMinPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(fechaMaxPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 120));

        tablaListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. Producto", "Nombre Producto", "Talla", "Cantidad Vendida", "Total Vendido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaListaProductos);
        if (tablaListaProductos.getColumnModel().getColumnCount() > 0) {
            tablaListaProductos.getColumnModel().getColumn(0).setResizable(false);
            tablaListaProductos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tablaListaProductos.getColumnModel().getColumn(0).setHeaderValue("Nro.");
            tablaListaProductos.getColumnModel().getColumn(1).setResizable(false);
            tablaListaProductos.getColumnModel().getColumn(2).setResizable(false);
            tablaListaProductos.getColumnModel().getColumn(3).setResizable(false);
            tablaListaProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 6, 588, 343));

        btnImprimirPro.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirPro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnImprimirPro.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirPro.setText("IMPRIMIR REPORTE");
        btnImprimirPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirProActionPerformed(evt);
            }
        });
        jPanel4.add(btnImprimirPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        jTabbedPane1.addTab("Listado de Productos Más Vendidos", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Intervalo de Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 12))); // NOI18N

        jLabel6.setText("Seleccionar Fecha Inicio:");

        jLabel7.setText("Seleccionar Fecha Fin:");

        btnListarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarCliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaMinCli, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(fechaMaxCli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(fechaMinCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(fechaMaxCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 120));

        btnImprimirCli.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirCli.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnImprimirCli.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirCli.setText("IMPRIMIR REPORTE");
        btnImprimirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCliActionPerformed(evt);
            }
        });
        jPanel9.add(btnImprimirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        tablaListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Veces que ha ingresado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaListaClientes);
        if (tablaListaClientes.getColumnModel().getColumnCount() > 0) {
            tablaListaClientes.getColumnModel().getColumn(0).setResizable(false);
            tablaListaClientes.getColumnModel().getColumn(1).setResizable(false);
            tablaListaClientes.getColumnModel().getColumn(2).setResizable(false);
            tablaListaClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 6, 588, 140));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        TablaTotalClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Correo Electronico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TablaTotalClientes);
        if (TablaTotalClientes.getColumnModel().getColumnCount() > 0) {
            TablaTotalClientes.getColumnModel().getColumn(0).setResizable(false);
            TablaTotalClientes.getColumnModel().getColumn(1).setResizable(false);
            TablaTotalClientes.getColumnModel().getColumn(2).setResizable(false);
            TablaTotalClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 580, 160));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel8.setText("LISTA COMPLETA DE CLIENTES");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jTabbedPane1.addTab("Listado de Clientes Que Ingresan al Sistema", jPanel9);

        jPanel5.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 830, 390));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 850, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        MenuAdmin admin = new MenuAdmin();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
        // Obtiene las fechas de los JDateChooser
        java.util.Date fechaInicio = fechaMin.getDate();
        java.util.Date fechaFin = fechaMax.getDate();
        java.util.Date fechaActualDate = new java.util.Date(); // Fecha actual

        // Verifica que las fechas no sean nulas
        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.");
            return;
        }

        // Verifica que la fecha de inicio no sea después de la fecha de fin
        if (fechaInicio.after(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser después de la fecha de fin.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verifica que las fechas no superen la fecha actual
        if (fechaInicio.after(fechaActualDate) || fechaFin.after(fechaActualDate)) {
            JOptionPane.showMessageDialog(this, "Las fechas no pueden ser posteriores a la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Formatea las fechas a String en formato yyyy-MM-dd
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaInicioStr = sdf.format(fechaInicio);
        String fechaFinStr = sdf.format(fechaFin);

        // Conecta a la base de datos
        ConexionBD conexion = new ConexionBD();
        conexion.conectar();

        try {
            // Llama al Stored Procedure para obtener las facturas en el intervalo de fechas
            String sp = "{CALL sp_obtenerFacturasPorFechas(?, ?)}";
            CallableStatement cs = conexion.conn.prepareCall(sp);
            cs.setString(1, fechaInicioStr);
            cs.setString(2, fechaFinStr);

            // Ejecuta el SP y obtiene los resultados
            ResultSet rs = cs.executeQuery();

            // Configura el modelo de la tabla
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Factura");
            model.addColumn("Cédula del Usuario");
            model.addColumn("Total");
            model.addColumn("IVA");
            model.addColumn("Fecha");
            model.addColumn("Método de Pago");
            model.addColumn("Subtotal");

            // Llena la tabla con los datos obtenidos
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID Factura"),
                    rs.getString("Cédula del Usuario"),
                    rs.getDouble("Total"),
                    rs.getDouble("IVA"),
                    rs.getDate("Fecha"),
                    rs.getInt("Método de Pago"),
                    rs.getDouble("Subtotal")
                });
            }

            tablaListaFacturas.setModel(model);
            btnImprimir.setEnabled(true);
            rs.close();
            cs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar las facturas: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            conexion.desconectar();
        }
    }//GEN-LAST:event_btnListarMouseClicked

    private void btnCalcularGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGananciasActionPerformed

        // Obtiene las fechas de los JDateChooser
        java.util.Date fechaInicio = fechaMin.getDate();
        java.util.Date fechaFin = fechaMax.getDate();

        // Verifica que las fechas no sean nulas
        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.");
            return;
        }

        // Formatea las fechas a String en formato yyyy-MM-dd
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaInicioStr = sdf.format(fechaInicio);
        String fechaFinStr = sdf.format(fechaFin);

        // Conecta a la base de datos
        ConexionBD conexion = new ConexionBD();
        conexion.conectar();

        try {
            // Llama a la función TotalVentasEnPeriodo
            String sql = "{ ? = CALL TotalVentasEnPeriodo(?, ?) }";
            CallableStatement cs = conexion.conn.prepareCall(sql);
            cs.registerOutParameter(1, Types.DOUBLE);
            cs.setString(2, fechaInicioStr);
            cs.setString(3, fechaFinStr);

            // Ejecuta la llamada a la función
            cs.execute();

            // Obtiene el resultado
            double totalGanancias = cs.getDouble(1);

            // Formatea el resultado a dos decimales
            DecimalFormat df = new DecimalFormat("#.00");
            String totalGananciasFormateado = df.format(totalGanancias);

            // Muestra el resultado en un JOptionPane
            fieldTotalGanancias.setText("Total de Ventas: " + totalGananciasFormateado);

            cs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al calcular las ganancias: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            conexion.desconectar();
        }


    }//GEN-LAST:event_btnCalcularGananciasActionPerformed

    private void btnListarProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProMouseClicked
        java.util.Date fechaInicio = fechaMinPro.getDate();
        java.util.Date fechaFin = fechaMaxPro.getDate();
        java.util.Date fechaActualDate = new java.util.Date(); // Fecha actual

        // Verifica que las fechas no sean nulas
        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.");
            return;
        }

        // Verifica que la fecha de inicio no sea después de la fecha de fin
        if (fechaInicio.after(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser después de la fecha de fin.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verifica que las fechas no superen la fecha actual
        if (fechaInicio.after(fechaActualDate) || fechaFin.after(fechaActualDate)) {
            JOptionPane.showMessageDialog(this, "Las fechas no pueden ser posteriores a la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convierte java.util.Date a java.sql.Date
        java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
        java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());

        // Llama al método para llenar la tabla
        llenarTablaProductos(sqlFechaInicio, sqlFechaFin);
        btnImprimirPro.setEnabled(true);
    }//GEN-LAST:event_btnListarProMouseClicked

    private void btnListarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarCliMouseClicked

        java.util.Date fechaInicio = fechaMinCli.getDate();
        java.util.Date fechaFin = fechaMaxCli.getDate();

        // Verifica que las fechas no sean nulas
        if (fechaInicio == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.");
            return;
        }

        // Verifica que la fecha de inicio no sea después de la fecha de fin
        if (fechaInicio.after(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser después de la fecha de fin.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convierte java.util.Date a java.sql.Date
        java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
        java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());

        // Llama al método para llenar la tabla
        llenarTablaClientes(sqlFechaInicio, sqlFechaFin);
        btnImprimirCli.setEnabled(true);
        cargarClientes();
    }//GEN-LAST:event_btnListarCliMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        GenerarReporteFacturaPDF reportePDF = new GenerarReporteFacturaPDF(fechaMin, fechaMax, fieldTotalGanancias);
        reportePDF.generarReporteFacturas(tablaListaFacturas);
        String rutaPDF = "C:\\Users\\USER\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoAula\\Reportes"; // reemplaza con la ruta real del directorio donde se generan los PDF
        File dir = new File(rutaPDF);
        File[] files = dir.listFiles((dir1, name) -> name.endsWith(".pdf"));
        Arrays.sort(files, (f1, f2) -> Long.compare(f2.lastModified(), f1.lastModified()));
        File lastPdf = files[0];
        try {
            Desktop desktop = Desktop.getDesktop();
            desktop.open(lastPdf);
            System.out.println("Reporte impreso correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnImprimirProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirProActionPerformed
        ProductosListaPDF reportePDF = new ProductosListaPDF(fechaMinPro, fechaMaxPro);
        reportePDF.generarReporteProductos(tablaListaProductos);
        String rutaPDF = "C:\\Users\\USER\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoAula\\ReporteProductos"; // reemplaza con la ruta real del directorio donde se generan los PDF
        File dir = new File(rutaPDF);
        File[] files = dir.listFiles((dir1, name) -> name.endsWith(".pdf"));
        Arrays.sort(files, (f1, f2) -> Long.compare(f2.lastModified(), f1.lastModified()));
        File lastPdf = files[0];
        try {
            Desktop desktop = Desktop.getDesktop();
            desktop.open(lastPdf);
            System.out.println("Reporte impreso correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnImprimirProActionPerformed

    private void btnImprimirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCliActionPerformed
        ClientesListaPDF reportePDF = new ClientesListaPDF(fechaMinCli, fechaMaxCli);
        reportePDF.generarReporteClientes(tablaListaClientes, TablaTotalClientes);
        String rutaPDF = "C:\\Users\\USER\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoAula\\ReporteClientes"; // reemplaza con la ruta real del directorio donde se generan los PDF
        File dir = new File(rutaPDF);
        File[] files = dir.listFiles((dir1, name) -> name.endsWith(".pdf"));
        Arrays.sort(files, (f1, f2) -> Long.compare(f2.lastModified(), f1.lastModified()));
        File lastPdf = files[0];
        try {
            Desktop desktop = Desktop.getDesktop();
            desktop.open(lastPdf);
            System.out.println("Reporte impreso correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo PDF: " + e.getMessage());
        }

    }//GEN-LAST:event_btnImprimirCliActionPerformed

    private void cargarClientes() {
        DefaultTableModel modelo = (DefaultTableModel) TablaTotalClientes.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        String sp = "{CALL sp_obtenerClientes()}"; // Llamada al Stored Procedure

        try (CallableStatement cs = conexion.conn.prepareCall(sp); ResultSet rs = cs.executeQuery()) {

            while (rs.next()) {
                Object[] row = {
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getString("cedula"),
                    rs.getString("correo")
                };
                modelo.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void llenarTablaClientes(java.sql.Date fechaInicio, java.sql.Date fechaFin) {
        DefaultTableModel modelo = (DefaultTableModel) tablaListaClientes.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        String sp = "{CALL sp_obtenerClientesPorFechas(?, ?)}"; // Llamada al Stored Procedure

        try (CallableStatement cs = conexion.conn.prepareCall(sp)) {
            cs.setDate(1, fechaInicio);
            cs.setDate(2, fechaFin);

            try (ResultSet rs = cs.executeQuery()) {
                while (rs.next()) {
                    String nombre = rs.getString("nombre");
                    String apellido = rs.getString("apellido");
                    String cedula = rs.getString("cedula");
                    int vecesQueHaEntrado = rs.getInt("veces_que_ha_entrado");

                    // Agregar los datos a la tabla
                    modelo.addRow(new Object[]{nombre, apellido, cedula, vecesQueHaEntrado});

                    // Imprimir en consola
                    System.out.println("Nombre: " + nombre);
                    System.out.println("Apellido: " + apellido);
                    System.out.println("Cédula: " + cedula);
                    System.out.println("Veces que ha entrado: " + vecesQueHaEntrado);
                    System.out.println("---------------------------");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void llenarTablaProductos(java.sql.Date fechaInicio, java.sql.Date fechaFin) {
        DefaultTableModel modelo = (DefaultTableModel) tablaListaProductos.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        String sp = "{CALL sp_obtenerProductosVendidosPorFechas(?, ?)}"; // Llamada al Stored Procedure

        try (CallableStatement cs = conexion.conn.prepareCall(sp)) {
            cs.setDate(1, fechaInicio);
            cs.setDate(2, fechaFin);

            try (ResultSet rs = cs.executeQuery()) {
                while (rs.next()) {
                    Object[] row = {
                        rs.getInt("ID Producto"),
                        rs.getString("Nombre Producto"),
                        rs.getString("Talla"),
                        rs.getInt("Cantidad Vendida"),
                        rs.getDouble("Total Vendido")
                    };
                    modelo.addRow(row);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTotalClientes;
    private javax.swing.JButton btnCalcularGanancias;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimirCli;
    private javax.swing.JButton btnImprimirPro;
    private javax.swing.JLabel btnListar;
    private javax.swing.JLabel btnListarCli;
    private javax.swing.JLabel btnListarPro;
    private com.toedter.calendar.JDateChooser fechaMax;
    private com.toedter.calendar.JDateChooser fechaMaxCli;
    private com.toedter.calendar.JDateChooser fechaMaxPro;
    private com.toedter.calendar.JDateChooser fechaMin;
    private com.toedter.calendar.JDateChooser fechaMinCli;
    private com.toedter.calendar.JDateChooser fechaMinPro;
    private javax.swing.JTextField fieldTotalGanancias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tablaListaClientes;
    private javax.swing.JTable tablaListaFacturas;
    private javax.swing.JTable tablaListaProductos;
    // End of variables declaration//GEN-END:variables
}
