/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoaula;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaLogin extends javax.swing.JFrame {

    public VentanaLogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        UtilidadesImagen.escalar(lblLogo, "C:/Users/USER/OneDrive/Escritorio/ProyectoAula/imgs/logo.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        fieldUsuario = new javax.swing.JTextField();
        fieldContrasenia = new javax.swing.JPasswordField();
        CheckMostrarPass = new javax.swing.JCheckBox();
        btnRecuperarContraseña = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JLabel();
        BtnRegistrarseNuevo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();

        lblLogo.setText("jLabel3");

        lblLogin.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("INICIAR SESIÓN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        fieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        fieldUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldUsuario.setText("Ingrese su nombre de usuario.");
        fieldUsuario.setBorder(null);
        fieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldUsuarioMousePressed(evt);
            }
        });

        fieldContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        fieldContrasenia.setText("********");
        fieldContrasenia.setBorder(null);
        fieldContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldContraseniaMousePressed(evt);
            }
        });

        CheckMostrarPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CheckMostrarPass.setText("Mostrar contraseña");
        CheckMostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMostrarPassActionPerformed(evt);
            }
        });

        btnRecuperarContraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnRecuperarContraseña.setText("Olvidaste tu contraseña");
        btnRecuperarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecuperarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperarContraseñaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnEntrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BtnRegistrarseNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnRegistrarseNuevo.setText("¿No tiene cuenta? Registrare Aqui");
        BtnRegistrarseNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrarseNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarseNuevoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese su nombre de usuario");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese su contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BtnRegistrarseNuevo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(CheckMostrarPass)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRecuperarContraseña))
                                .addComponent(fieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(fieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckMostrarPass)
                    .addComponent(btnRecuperarContraseña))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegistrarseNuevo)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 430, 400));
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean mostrarContrasenia = false;


    private void CheckMostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMostrarPassActionPerformed
        if (mostrarContrasenia) {
            fieldContrasenia.setEchoChar('*');
            mostrarContrasenia = false;
        } else {
            fieldContrasenia.setEchoChar((char) 0);
            mostrarContrasenia = true;
        }
    }//GEN-LAST:event_CheckMostrarPassActionPerformed

    private void fieldUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldUsuarioMousePressed
        if (fieldUsuario.getText().equals("Ingrese su nombre de usuario.")) {
            fieldUsuario.setText("");
            fieldUsuario.setForeground(Color.black);
        }
        if (String.valueOf(fieldContrasenia.getPassword()).isEmpty()) {
            fieldContrasenia.setText("********");
            fieldContrasenia.setForeground(Color.gray);
        }
    }//GEN-LAST:event_fieldUsuarioMousePressed

    private void fieldContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldContraseniaMousePressed
        if (String.valueOf(fieldContrasenia.getPassword()).equals("********")) {
            fieldContrasenia.setText("");
            fieldContrasenia.setForeground(Color.black);
        }
        if (fieldUsuario.getText().isEmpty()) {
            fieldUsuario.setText("Ingrese su nombre de usuario.");
            fieldUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_fieldContraseniaMousePressed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked

        String usuario = fieldUsuario.getText();
        String contrasenia = new String(fieldContrasenia.getPassword());

        ConexionBD conexion = new ConexionBD();
        conexion.conectar();

        try {
            // Consulta para obtener la cédula del usuario
            String sqlUsuarios = "SELECT usu_cedula FROM Usuarios WHERE usu_usuario=? AND usu_clave=?";
            PreparedStatement psUsuarios = conexion.conn.prepareStatement(sqlUsuarios);
            psUsuarios.setString(1, usuario);
            psUsuarios.setString(2, contrasenia);
            ResultSet rsUsuarios = psUsuarios.executeQuery();

            if (rsUsuarios.next()) {
                // Obtiene la cédula y la muestra en lblCedula
                String cedula = rsUsuarios.getString("usu_cedula");
                Sesion.setCedula(cedula);

                // Mensaje de éxito
                System.out.println("Inicio de sesión exitoso");

                // Abre la ventana correspondiente según el usuario
                if (usuario.equals("admin") && contrasenia.equals("admin")) {
                    RegistrarUsuario ventanaRegistro = new RegistrarUsuario();
                    ventanaRegistro.setVisible(true);
                    this.dispose();
                } else {
                    Productos ventanaProductos = new Productos();
                    ventanaProductos.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                lblCedula.setText(""); // Limpia el label si las credenciales son incorrectas
            }

            rsUsuarios.close();
            psUsuarios.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en la conexión a la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            conexion.desconectar();
        }

    }//GEN-LAST:event_btnEntrarMouseClicked

    private void BtnRegistrarseNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarseNuevoMouseClicked
        RegistrarUsuario registro = new RegistrarUsuario();
        registro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnRegistrarseNuevoMouseClicked

    private void btnRecuperarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarContraseñaMouseClicked
        RecuperacionContrasenia recuperar = new RecuperacionContrasenia();
        recuperar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRecuperarContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnRegistrarseNuevo;
    private javax.swing.JCheckBox CheckMostrarPass;
    private javax.swing.JLabel btnEntrar;
    private javax.swing.JLabel btnRecuperarContraseña;
    private javax.swing.JPasswordField fieldContrasenia;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
